# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(FFEFE6)
$foreground = rgb(141415)
$color0 = rgb(FFFAF1)
$color1 = rgb(9E5135)
$color2 = rgb(5D696D)
$color3 = rgb(4A5256)
$color4 = rgb(4F3530)
$color5 = rgb(252527)
$color6 = rgb(212123)
$color7 = rgb(141415)
$color8 = rgb(A55D43)
$color9 = rgb(D26C46)
$color10 = rgb(7C8C91)
$color11 = rgb(636E72)
$color12 = rgb(6A4740)
$color13 = rgb(313234)
$color14 = rgb(2C2C2E)
$color15 = rgb(070707)
